### ISSUE TITLE
Inicio_de_sesión-Error de PHP

### ISSUE THREAD

**Issue by LilyArteaga** [guagnelli/sipimss#2]
Al intentar ingresar con el usuario 311091404, se muestra lo siguiente:

A PHP Error was encountered
Severity: Warning
Message: Creating default object from empty value
Filename: models/Login_model.php
Line Number: 171
Backtrace:
File: C:\Bitnami\wampstack\apache2\htdocs\sipimss\application\models\Login_model.php
Line: 171
Function: _error_handler
File: C:\Bitnami\wampstack\apache2\htdocs\sipimss\application\helpers\manejo_general_model_helper.php
Line: 206
Function: set_login_user
File: C:\Bitnami\wampstack\apache2\htdocs\sipimss\application\controllers\Login.php
Line: 51
Function: iniciar_sesion
File: C:\Bitnami\wampstack\apache2\htdocs\sipimss\index.php
Line: 315
Function: require_once

![image](https://cloud.githubusercontent.com/assets/22103164/18414511/3dcf89fa-7791-11e6-9a1e-949821074eeb.png)

**Comment by guagnelli** [comment]
Se corrigió, al tratar de enviar un usuario no registrado en el inicio de sesión
